import { BarcodeDisplay } from "@/components/product/barcode-display";
import { PhotoPicker } from "@/components/ui/photo-picker";
import { UnitPicker } from "@/components/ui/unit-picker";
import { useColors } from "@/hooks/use-colors";
import type { CreateProductInput, Product, SaleMode } from "@/models/product";
import type { Unit } from "@/models/unit";
import { Eye, EyeOff } from "@tamagui/lucide-icons";
import { useId, useState } from "react";
import { Switch } from "react-native";
import { Button, Input, Label, Spinner, Text, XStack, YStack } from "tamagui";

// ── ProductForm (create + edit) ───────────────────────────────────────────────
// Pass `product` to enter edit mode. Omit it for create mode.

export interface ProductFormProps {
  /** Providing this switches to edit mode (fields pre-filled, barcode read-only). */
  product?: Product;
  /** Required in create mode — fresh EAN-13 generated by the parent. */
  barcode?: string;
  /** Whether the barcode was obtained via scanning (vs auto-generated). */
  scanned?: boolean;
  units: Unit[];
  onSubmit: (data: CreateProductInput) => void;
  loading?: boolean;
}

export function ProductForm({
  product,
  barcode: barcodeProp,
  scanned,
  units,
  onSubmit,
  loading,
}: ProductFormProps) {
  const uid = useId();
  const c = useColors();
  const isEdit = product !== undefined;
  const barcode = isEdit ? product.barcode : barcodeProp ?? "";

  const [name, setName] = useState(isEdit ? product.name : "");
  const [costPrice, setCostPrice] = useState(
    isEdit ? String(product.costPrice) : "",
  );
  const [salePrice, setSalePrice] = useState(
    isEdit ? String(product.salePrice) : "",
  );
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [stock, setStock] = useState(
    isEdit ? String(product.stockBaseQty) : "0",
  );
  const [unitId, setUnitId] = useState(
    isEdit ? String(product.baseUnitId) : "",
  );
  const [saleMode, setSaleMode] = useState<SaleMode>(
    isEdit ? product.saleMode : "UNIT",
  );
  const [photoUri, setPhotoUri] = useState<string | null>(
    isEdit ? product.photoUri ?? null : null,
  );
  const [visible, setVisible] = useState(isEdit ? product.visible : true);

  const parsedCost = parseFloat(costPrice);
  const parsedSale = parseFloat(salePrice);
  const canSubmit =
    name.trim().length > 0 &&
    !isNaN(parsedCost) &&
    parsedCost > 0 &&
    (!isEdit || (!isNaN(parsedSale) && parsedSale > 0)) &&
    unitId.length > 0;

  const handleSubmit = () => {
    if (!canSubmit) return;
    onSubmit({
      name: name.trim(),
      barcode,
      pricePerBaseUnit: parsedCost,
      costPrice: parsedCost,
      salePrice: isEdit ? parsedSale : parsedCost, // create: salePrice = costPrice initially
      visible,
      stockBaseQty: isEdit ? product.stockBaseQty : 0, // always 0 on create
      saleMode,
      baseUnitId: parseInt(unitId, 10),
      photoUri,
    });
  };

  return (
    <YStack gap="$3" p="$4">
      {/* Photo */}
      <YStack gap="$1">
        <Label color="$color10" fontSize="$3">
          Foto del producto
        </Label>
        <PhotoPicker uri={photoUri} onChange={setPhotoUri} />
      </YStack>

      {/* Barcode */}
      <YStack
        bg="$color1"
        style={{ borderRadius: 12, alignItems: "center" }}
        p="$3"
        gap="$2"
      >
        <BarcodeDisplay barcode={barcode} width={260} barHeight={50} />
        <Text fontSize="$2" color="$color10" letterSpacing={2}>
          {barcode}
        </Text>
        <Text fontSize="$1" color="$color8">
          {isEdit
            ? "El código de barras no puede modificarse"
            : scanned
            ? "Código obtenido por escaneo"
            : "Código generado automáticamente"}
        </Text>
      </YStack>

      {/* Name */}
      <YStack gap="$1">
        <Label htmlFor={`${uid}-name`} color="$color10" fontSize="$3">
          Nombre
        </Label>
        <Input
          id={`${uid}-name`}
          placeholder="Nombre del producto"
          value={name}
          onChangeText={setName}
          returnKeyType="done"
          size="$4"
        />
      </YStack>

      {/* Cost price (always shown) + Sale price (edit only) */}
      <XStack gap="$3">
        <YStack flex={1} gap="$1">
          <Label htmlFor={`${uid}-cost`} color="$color10" fontSize="$3">
            Precio costo
          </Label>
          <Input
            id={`${uid}-cost`}
            placeholder="0.00"
            value={costPrice}
            onChangeText={setCostPrice}
            keyboardType="decimal-pad"
            returnKeyType="done"
            size="$4"
          />
        </YStack>

        {isEdit && (
          <YStack flex={1} gap="$1">
            <Label htmlFor={`${uid}-sale`} color="$color10" fontSize="$3">
              Precio venta
            </Label>
            <Input
              id={`${uid}-sale`}
              placeholder="0.00"
              value={salePrice}
              onChangeText={setSalePrice}
              keyboardType="decimal-pad"
              returnKeyType="done"
              size="$4"
            />
          </YStack>
        )}
      </XStack>

      {/* Unit */}
      <YStack gap="$1">
        <Label color="$color10" fontSize="$3">
          Unidad base
        </Label>
        <UnitPicker units={units} value={unitId} onChange={setUnitId} />
      </YStack>

      {/* Sale mode */}
      <YStack gap="$1">
        <Label color="$color10" fontSize="$3">
          Modo de venta
        </Label>
        <XStack gap="$2">
          <Button
            flex={1}
            theme={saleMode === "UNIT" ? "blue" : undefined}
            onPress={() => setSaleMode("UNIT")}
            size="$4"
          >
            Por unidad
          </Button>
          <Button
            flex={1}
            theme={saleMode === "VARIABLE" ? "blue" : undefined}
            onPress={() => setSaleMode("VARIABLE")}
            size="$4"
          >
            Variable
          </Button>
        </XStack>
      </YStack>

      {/* Visible to workers (edit only) */}
      {isEdit && (
        <XStack
          gap="$3"
          style={{ alignItems: "center", justifyContent: "space-between" }}
        >
          <XStack gap="$2" style={{ alignItems: "center", flex: 1 }}>
            {visible ? (
              <Eye size={18} color="$green10" />
            ) : (
              <EyeOff size={18} color="$color8" />
            )}
            <Label
              color="$color10"
              fontSize="$3"
              style={{ margin: 0, lineHeight: 18 }}
            >
              Visible para vendedores
            </Label>
          </XStack>
          <Switch
            value={visible}
            onValueChange={setVisible}
            trackColor={{ false: c.border, true: c.blue }}
          />
        </XStack>
      )}

      <Button
        size="$5"
        theme="blue"
        mt="$2"
        disabled={loading || !canSubmit}
        onPress={handleSubmit}
        icon={loading ? <Spinner /> : undefined}
      >
        {loading
          ? "Guardando..."
          : isEdit
          ? "Guardar cambios"
          : "Crear producto"}
      </Button>
    </YStack>
  );
}
