import { BarcodeDisplay } from "@/components/product/barcode-display";
import { PhotoPicker } from "@/components/ui/photo-picker";
import { UnitPicker } from "@/components/ui/unit-picker";
import type { CreateProductInput, Product, SaleMode } from "@/models/product";
import type { Unit } from "@/models/unit";
import { useState } from "react";
import { Button, Input, Label, Spinner, Text, XStack, YStack } from "tamagui";

// ── ProductForm (create + edit) ───────────────────────────────────────────────
// Pass `product` to enter edit mode. Omit it for create mode.

export interface ProductFormProps {
  /** Providing this switches to edit mode (fields pre-filled, barcode read-only). */
  product?: Product;
  /** Required in create mode — fresh EAN-13 generated by the parent. */
  barcode?: string;
  units: Unit[];
  onSubmit: (data: CreateProductInput) => void;
  loading?: boolean;
}

export function ProductForm({
  product,
  barcode: barcodeProp,
  units,
  onSubmit,
  loading,
}: ProductFormProps) {
  const isEdit = product !== undefined;
  const barcode = isEdit ? product.barcode : (barcodeProp ?? "");

  const [name, setName] = useState(isEdit ? product.name : "");
  const [price, setPrice] = useState(
    isEdit ? String(product.pricePerBaseUnit) : "",
  );
  const [stock, setStock] = useState(
    isEdit ? String(product.stockBaseQty) : "",
  );
  const [unitId, setUnitId] = useState(
    isEdit ? String(product.baseUnitId) : "",
  );
  const [saleMode, setSaleMode] = useState<SaleMode>(
    isEdit ? product.saleMode : "UNIT",
  );
  const [photoUri, setPhotoUri] = useState<string | null>(
    isEdit ? (product.photoUri ?? null) : null,
  );

  const parsedPrice = parseFloat(price);
  const parsedStock = parseFloat(stock);
  const canSubmit =
    name.trim().length > 0 &&
    !isNaN(parsedPrice) &&
    parsedPrice > 0 &&
    (isEdit || (!isNaN(parsedStock) && parsedStock >= 0)) &&
    unitId.length > 0;

  const handleSubmit = () => {
    if (!canSubmit) return;
    onSubmit({
      name: name.trim(),
      barcode,
      pricePerBaseUnit: parsedPrice,
      stockBaseQty: isEdit ? product.stockBaseQty : parsedStock,
      saleMode,
      baseUnitId: parseInt(unitId, 10),
      photoUri,
    });
  };

  return (
    <YStack gap="$3" p="$4">
      <Text fontSize="$6" fontWeight="bold" color="$color">
        {isEdit ? "Editar producto" : "Nuevo producto"}
      </Text>

      {/* Photo */}
      <YStack gap="$1">
        <Label color="$color10" fontSize="$3">
          Foto del producto
        </Label>
        <PhotoPicker uri={photoUri} onChange={setPhotoUri} />
      </YStack>

      {/* Barcode */}
      <YStack
        bg="$color1"
        style={{ borderRadius: 12, alignItems: "center" }}
        p="$3"
        gap="$2"
      >
        <BarcodeDisplay barcode={barcode} width={260} barHeight={50} />
        <Text fontSize="$2" color="$color10" letterSpacing={2}>
          {barcode}
        </Text>
        <Text fontSize="$1" color="$color8">
          {isEdit
            ? "El código de barras no puede modificarse"
            : "Código generado automáticamente"}
        </Text>
      </YStack>

      {/* Name */}
      <YStack gap="$1">
        <Label htmlFor="pf-name" color="$color10" fontSize="$3">
          Nombre
        </Label>
        <Input
          id="pf-name"
          placeholder="Nombre del producto"
          value={name}
          onChangeText={setName}
          returnKeyType="done"
          size="$4"
        />
      </YStack>

      {/* Price + Stock (stock only shown when creating) */}
      <XStack gap="$3">
        <YStack flex={1} gap="$1">
          <Label htmlFor="pf-price" color="$color10" fontSize="$3">
            Precio
          </Label>
          <Input
            id="pf-price"
            placeholder="0.00"
            value={price}
            onChangeText={setPrice}
            keyboardType="decimal-pad"
            returnKeyType="done"
            size="$4"
          />
        </YStack>

        {!isEdit && (
          <YStack flex={1} gap="$1">
            <Label htmlFor="pf-stock" color="$color10" fontSize="$3">
              Stock inicial
            </Label>
            <Input
              id="pf-stock"
              placeholder="0"
              value={stock}
              onChangeText={setStock}
              keyboardType="numeric"
              returnKeyType="done"
              size="$4"
            />
          </YStack>
        )}
      </XStack>

      {/* Unit */}
      <YStack gap="$1">
        <Label color="$color10" fontSize="$3">
          Unidad base
        </Label>
        <UnitPicker units={units} value={unitId} onChange={setUnitId} />
      </YStack>

      {/* Sale mode */}
      <YStack gap="$1">
        <Label color="$color10" fontSize="$3">
          Modo de venta
        </Label>
        <XStack gap="$2">
          <Button
            flex={1}
            theme={saleMode === "UNIT" ? "blue" : undefined}
            onPress={() => setSaleMode("UNIT")}
            size="$4"
          >
            Por unidad
          </Button>
          <Button
            flex={1}
            theme={saleMode === "VARIABLE" ? "blue" : undefined}
            onPress={() => setSaleMode("VARIABLE")}
            size="$4"
          >
            Variable
          </Button>
        </XStack>
      </YStack>

      <Button
        size="$5"
        theme="blue"
        mt="$2"
        disabled={loading || !canSubmit}
        onPress={handleSubmit}
        icon={loading ? <Spinner /> : undefined}
      >
        {loading
          ? "Guardando..."
          : isEdit
            ? "Guardar cambios"
            : "Crear producto"}
      </Button>
    </YStack>
  );
}
