import { BarcodeDisplay } from "@/components/product/barcode-display";
import {
    PriceTierEditorRow,
    PriceTiersEditor,
    normalizePriceTierRows,
    validatePriceTierRows,
} from "@/components/product/price-tiers-editor";
import { PhotoPicker } from "@/components/ui/photo-picker";
import { UnitPicker } from "@/components/ui/unit-picker";
import { useColors } from "@/hooks/use-colors";
import type { CreateProductInput, Product, SaleMode } from "@/models/product";
import type { Unit } from "@/models/unit";
import { Eye, EyeOff } from "@tamagui/lucide-icons";
import { useEffect, useId, useState } from "react";
import { ScrollView, Switch, View } from "react-native";
import QRCode from "react-native-qrcode-svg";
import { Button, Input, Label, Spinner, Text, XStack, YStack } from "tamagui";

// ── ProductForm (create + edit) ───────────────────────────────────────────────
// Pass `product` to enter edit mode. Omit it for create mode.

export interface ProductFormProps {
  /** Providing this switches to edit mode (fields pre-filled, barcode read-only). */
  product?: Product;
  /** Required in create mode — fresh EAN-13 generated by the parent. */
  code?: string;
  /** Whether the code was obtained via scanning (vs auto-generated). */
  scanned?: boolean;
  units: Unit[];
  onSubmit: (data: CreateProductInput) => void;
  loading?: boolean;
  onCancel?: () => void;
}

export function ProductForm({
  product,
  code: codeProp,
  scanned,
  units,
  onSubmit,
  loading,
  onCancel,
}: ProductFormProps) {
  const uid = useId();
  const c = useColors();
  const isEdit = product !== undefined;
  const code = isEdit ? product.code : codeProp ?? "";

  const [name, setName] = useState(isEdit ? product.name : "");
  const [costPrice, setCostPrice] = useState(
    isEdit ? String(product.costPrice) : "",
  );
  const [salePrice, setSalePrice] = useState(
    isEdit ? String(product.salePrice) : "",
  );
  const [stock, setStock] = useState(
    isEdit ? String(product.stockBaseQty) : "",
  );
  const [unitId, setUnitId] = useState(
    isEdit ? String(product.baseUnitId) : "",
  );
  const [saleMode, setSaleMode] = useState<SaleMode>(
    isEdit ? product.saleMode : "UNIT",
  );
  const [photoUri, setPhotoUri] = useState<string | null>(
    isEdit ? product.photoUri ?? null : null,
  );
  const [visible, setVisible] = useState(isEdit ? product.visible : true);
  const [details, setDetails] = useState(isEdit ? product.details ?? "" : "");
  const [tierRows, setTierRows] = useState<PriceTierEditorRow[]>(() =>
    isEdit
      ? (product.priceTiers ?? []).map((tier) => ({
          id: tier.id,
          minQty: String(tier.minQty),
          maxQty: tier.maxQty === null ? "" : String(tier.maxQty),
          price: String(tier.price),
        }))
      : [],
  );

  useEffect(() => {
    if (isEdit) {
      setTierRows(
        (product.priceTiers ?? []).map((tier) => ({
          id: tier.id,
          minQty: String(tier.minQty),
          maxQty: tier.maxQty === null ? "" : String(tier.maxQty),
          price: String(tier.price),
        })),
      );
    } else {
      setTierRows([]);
    }
  }, [isEdit, product]);

  const parsedCost = parseFloat(costPrice);
  const parsedSale = parseFloat(salePrice);
  const parsedStock = parseFloat(stock);
  const tierError = validatePriceTierRows(tierRows);
  const normalizedTiers = normalizePriceTierRows(tierRows);

  const canSubmit =
    name.trim().length > 0 &&
    !isNaN(parsedCost) &&
    parsedCost > 0 &&
    !isNaN(parsedSale) &&
    parsedSale > 0 &&
    !isNaN(parsedStock) &&
    parsedStock >= 0 &&
    unitId.length > 0 &&
    !tierError;

  const handleSubmit = () => {
    if (!canSubmit) return;
    onSubmit({
      name: name.trim(),
      code,
      pricePerBaseUnit: parsedCost,
      costPrice: parsedCost,
      salePrice: parsedSale,
      visible,
      stockBaseQty: parsedStock,
      saleMode,
      baseUnitId: parseInt(unitId, 10),
      photoUri,
      details: details.trim() || null,
      priceTiers: normalizedTiers.length > 0 ? normalizedTiers : undefined,
    });
  };

  return (
    <View style={{ flex: 1 }}>
      <ScrollView
        keyboardShouldPersistTaps="handled"
        automaticallyAdjustKeyboardInsets
        contentContainerStyle={{ paddingBottom: 140 }}
        style={{ flex: 1 }}
      >
        <YStack gap="$3" p="$4">
          {/* Photo */}
          <YStack gap="$1">
            <Label color="$color10" fontSize="$3">
              Foto del producto
            </Label>
            <PhotoPicker uri={photoUri} onChange={setPhotoUri} />
          </YStack>

          {/* Code (barcode + QR) */}
          <YStack bg="$color1" style={{ borderRadius: 12 }} p="$3" gap="$2">
            <XStack gap="$2.5">
              <YStack
                flex={2}
                bg="white"
                style={{
                  borderRadius: 10,
                  overflow: "hidden",
                  alignItems: "center",
                  justifyContent: "center",
                }}
                py="$2"
              >
                <BarcodeDisplay
                  code={code}
                  width={180}
                  barHeight={48}
                  showText={false}
                />
              </YStack>
              <YStack
                flex={1}
                bg="white"
                style={{
                  borderRadius: 10,
                  overflow: "hidden",
                  alignItems: "center",
                  justifyContent: "center",
                }}
                p="$2"
              >
                <QRCode value={code || " "} size={46} backgroundColor="white" />
              </YStack>
            </XStack>
            <Text
              fontSize="$2"
              color="$color10"
              letterSpacing={2}
              style={{ textAlign: "center" }}
            >
              {code}
            </Text>
            <Text fontSize="$1" color="$color8" style={{ textAlign: "center" }}>
              {isEdit
                ? "El código no puede modificarse"
                : scanned
                ? "Código obtenido por escaneo"
                : "Código generado automáticamente"}
            </Text>
          </YStack>

          {/* Name */}
          <YStack gap="$1">
            <Label htmlFor={`${uid}-name`} color="$color10" fontSize="$3">
              Nombre
            </Label>
            <Input
              id={`${uid}-name`}
              placeholder="Nombre del producto"
              value={name}
              onChangeText={setName}
              returnKeyType="next"
              size="$4"
            />
          </YStack>

          {/* Details */}
          <YStack gap="$1">
            <Label htmlFor={`${uid}-details`} color="$color10" fontSize="$3">
              Detalles
            </Label>
            <Input
              id={`${uid}-details`}
              placeholder="Descripción, ingredientes, notas…"
              value={details}
              onChangeText={setDetails}
              multiline
              numberOfLines={3}
              size="$4"
              style={{ minHeight: 80 }}
            />
          </YStack>

          {/* Cost price + Sale price */}
          <XStack gap="$3">
            <YStack flex={1} gap="$1">
              <Label htmlFor={`${uid}-cost`} color="$color10" fontSize="$3">
                Precio costo
              </Label>
              <Input
                id={`${uid}-cost`}
                placeholder="0.00"
                value={costPrice}
                onChangeText={setCostPrice}
                keyboardType="decimal-pad"
                returnKeyType="done"
                size="$4"
              />
            </YStack>

            <YStack flex={1} gap="$1">
              <Label htmlFor={`${uid}-sale`} color="$color10" fontSize="$3">
                Precio venta
              </Label>
              <Input
                id={`${uid}-sale`}
                placeholder="0.00"
                value={salePrice}
                onChangeText={setSalePrice}
                keyboardType="decimal-pad"
                returnKeyType="done"
                size="$4"
              />
            </YStack>
          </XStack>

          {/* Stock */}
          <YStack gap="$1">
            <Label htmlFor={`${uid}-stock`} color="$color10" fontSize="$3">
              {isEdit ? "Stock actual" : "Stock inicial"}
            </Label>
            <Input
              id={`${uid}-stock`}
              placeholder="0"
              value={stock}
              onChangeText={setStock}
              keyboardType="decimal-pad"
              returnKeyType="done"
              size="$4"
            />
          </YStack>

          {/* Unit */}
          <YStack gap="$1">
            <Label color="$color10" fontSize="$3">
              Unidad base
            </Label>
            <UnitPicker units={units} value={unitId} onChange={setUnitId} />
          </YStack>

          {/* Sale mode */}
          <YStack gap="$1">
            <Label color="$color10" fontSize="$3">
              Modo de venta
            </Label>
            <XStack gap="$2">
              <Button
                flex={1}
                theme={saleMode === "UNIT" ? "blue" : undefined}
                onPress={() => setSaleMode("UNIT")}
                size="$4"
              >
                Por unidad
              </Button>
              <Button
                flex={1}
                theme={saleMode === "VARIABLE" ? "blue" : undefined}
                onPress={() => setSaleMode("VARIABLE")}
                size="$4"
              >
                Variable
              </Button>
            </XStack>
          </YStack>

          <PriceTiersEditor
            rows={tierRows}
            onChange={setTierRows}
            error={tierError}
          />

          {/* Visible to workers (edit only) */}
          {isEdit && (
            <XStack
              gap="$3"
              style={{ alignItems: "center", justifyContent: "space-between" }}
            >
              <XStack gap="$2" style={{ alignItems: "center", flex: 1 }}>
                {visible ? (
                  <Eye size={18} color="$green10" />
                ) : (
                  <EyeOff size={18} color="$color8" />
                )}
                <Label
                  color="$color10"
                  fontSize="$3"
                  style={{ margin: 0, lineHeight: 18 }}
                >
                  Visible para vendedores
                </Label>
              </XStack>
              <Switch
                value={visible}
                onValueChange={setVisible}
                trackColor={{ false: c.border, true: c.blue }}
              />
            </XStack>
          )}
        </YStack>
      </ScrollView>

      {/* ── Fixed footer ───────────────────────────────────── */}
      <View
        style={{
          paddingHorizontal: 16,
          paddingVertical: 12,
          borderTopWidth: 1,
          borderTopColor: c.border,
          backgroundColor: c.modalBg,
        }}
      >
        <XStack gap="$2.5">
          {onCancel && (
            <Button flex={1} variant="outlined" onPress={onCancel} size="$5">
              Cancelar
            </Button>
          )}
          <Button
            flex={1}
            size="$5"
            theme="blue"
            disabled={loading || !canSubmit}
            opacity={loading || !canSubmit ? 0.5 : 1}
            onPress={handleSubmit}
            icon={loading ? <Spinner /> : undefined}
          >
            {loading ? "Guardando..." : isEdit ? "Guardar cambios" : "Crear"}
          </Button>
        </XStack>
      </View>
    </View>
  );
}
